package com.AniCare.demo.constant.medical;

public enum PetSpecies {
    DOG, CAT, PARROT, FERRET, HAMSTER, SQUIRREL, RABBIT, HEDGEHOG, MOUSE, TURTLE, FOX, MONKEY, PIG, DUCK, CHICKEN, COW, GUINEAPIG, CAMELEON, SNAKE, LIZARD, HORSE, MERCAT, SNAIL, FISH
}
