package com.AniCare.demo.constant.admin;

public enum ClinicType {
    DOG, CAT, PARROT, FERRET, HAMSTER, SQUIRREL, RABBIT, HEDGEHOG, MOUSE, TURTLE, FOX, MONKEY, PIG, DUCK, CHICKEN, COW, GUINEAPIG, CAMELEON, SNAKE, LIZARD, HORSE, MERCAT, SNAIL, FISH
}
